name = "FiniteMesh"
uuid = "d3ebd857-6980-4843-ad12-8da20c4645b4"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.3.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "^1"
julia = "^1"

[extras]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
build = ["Conda"]
test = ["Test"]
