name = "MeshArt"
uuid = "d3ebd857-6980-4843-ad12-8da20c4645b4"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
